// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR3_SecureAPI.Models;

#nullable disable

namespace PR3_SecureAPI.Migrations.Poste
{
    [DbContext(typeof(PosteContext))]
    partial class PosteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PR3_SecureAPI.Models.CommandePoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateExecution")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Portee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PosteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeCommande")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CommandesPostes");
                });

            modelBuilder.Entity("PR3_SecureAPI.Models.Etablissement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Etablissement");
                });

            modelBuilder.Entity("PR3_SecureAPI.Models.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseIP")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DisqueLibreGb")
                        .HasColumnType("REAL");

                    b.Property<double?>("DisqueTotalGb")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomMachine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RamDisponibleMb")
                        .HasColumnType("REAL");

                    b.Property<double?>("RamTotaleMb")
                        .HasColumnType("REAL");

                    b.Property<long>("SalleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Poste");
                });

            modelBuilder.Entity("PR3_SecureAPI.Models.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtablissementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salle");
                });
#pragma warning restore 612, 618
        }
    }
}
