// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR3_SecureAPI.Models;

#nullable disable

namespace PR3_SecureAPI.Migrations
{
    [DbContext(typeof(SalleContext))]
    [Migration("20260413175003_AddUniqueIndexSalleNumeroEtablissement")]
    partial class AddUniqueIndexSalleNumeroEtablissement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PR3_SecureAPI.Models.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtablissementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Numero", "EtablissementId")
                        .IsUnique();

                    b.ToTable("Salle");
                });
#pragma warning restore 612, 618
        }
    }
}
